template: 'umccr'

base_count_multiplier: 0.000000001
base_count_prefix: 'Gb'
base_count_desc: 'gigabases'

module_order:
    - dragen
    - purple
    - custom_content
    - bcftools:
        info: Bcftools stats for somatic variant calls.
        name: Bcftools stats (somatic)
        path_filters:
            - '*.somatic.bcftools_stats.txt'
    - bcftools:
        info: Bcftools stats for germline variant calls.
        name: Bcftools stats (germline)
        path_filters:
            - '*.germline.bcftools_stats.txt'
    - dragen_fastqc

custom_table_header_config:
    general_stats_table:
        ploidy:
            hidden: True
        purity:
            hidden: True
        avg_gc_content_percent:
            hidden: True

bcftools:
    collapse_complementary_changes: False
    write_separate_table: True
    write_general_stats: False

umccr:
    reference_samples:
        - Alice_T
        - Alice_B
        - Alice_N
        - Alice
        - Alice_normal
        - Bob_T
        - Bob_N
        - Bob_B
        - Bob
        - Bob_normal
        - Chen_T
        - Chen_N
        - Chen_B
        - Chen
        - Chen_normal
        - Dakota_T
        - Dakota_N
        - Dakota_B
        - Dakota
        - Dakota_normal
        - Elon_T
        - Elon_N
        - Elon_B
        - Elon
        - Elon_normal

custom_data:
    umccr:
        plot_type: generalstats
        pconfig:
        - subset_genes:
            title: 'Subset to key genes'
            description: 'Percentage of variants removed by subsetting to cancer genes. This happens when there are more than 500k calls to avoid choking the reporting'
            min: 0
            max: 100
            format: '{:,.2f}'
            suffix: '%'

        - filt_vars:
            title: 'Filt'
            description: '% variants filtered out by somatic filters (panel of normals, gnomAD common, homopolymers/LCR with low depth and AF)'
            min: 0
            max: 100
            format: '{:,.2f}'
            scale: 'Reds'
            suffix: '%'
            hidden: True
        - filt_snps:
            title: 'SNP-filt'
            description: '% SNPs filtered out by somatic filters (panel of normals, gnomAD common, homopolymers/LCR with low depth and AF)'
            min: 0
            max: 100
            format: '{:,.2f}'
            scale: 'Reds'
            suffix: '%'
            hidden: False
        - filt_indels:
            title: 'Indel-filt'
            description: '% Indels filtered out by somatic filters (panel of normals, gnomAD common, homopolymers/LCR with low depth and AF)'
            min: 0
            max: 100
            format: '{:,.2f}'
            scale: 'Reds'
            suffix: '%'
            hidden: False
        - filt_other:
            title: 'Other-filt'
            description: '% Other variants (MNP) filtered out by somatic filters (panel of normals, gnomAD common, homopolymers/LCR with low depth and AF)'
            min: 0
            max: 100
            format: '{:,.2f}'
            scale: 'Reds'
            suffix: '%'
            hidden: True

        - snps:
            title: 'SNP'
            description: 'Somatic SNPs passing UMCCR filters'
            min: 0
            format: '{:,.0f}'
        - indels:
            title: 'Indel'
            description: 'Somatic indels passing UMCCR filters'
            min: 0
            format: '{:,.0f}'
        - other:
            title: 'Other'
            description: 'Other somatic variants (MNP), passing UMCCR filters'
            min: 0
            format: '{:,.0f}'
            hidden: True

        - germline:
            title: 'Germline'
            description: 'Germline variants, as found by germline variant calling from the normal sample'
            min: 0
            format: '{:,.0f}'

sp:
    umccr:
        fn_re: '.*(somatic|germline).variant_counts.yaml'
